### ISSUE TITLE
OpenClinica DOM elements identification

### ISSUE THREAD

**Issue by marctc** [OpenClinica/OpenClinica#169]
As I could see in the official documentation the suggested method of getting values of DOM element in OpenClinica is using "children", "sibilings" and "parents" jquery methods:

http://en.wikibooks.org/wiki/OpenClinica_User_Manual/VarsFromHeader#How_does_it_work.3F

Are you planning in further versions identify DOM elements in a proper way? This method is prone to suffer several bugs or getting incorrect values if someone alters the field structure.

**Comment by toskrip** [comment]
If you are interested in CRF field values only (and not their HTML representation) you should consider to use token (${item[‘item_name’]}) introduced in OC 3.3. Alternatively you can also use OC RESTfull URLs. There you can navigate to CRF data field according to its OID.

**Comment by marctc** [comment]
@toskrip I think that I didn't exposed my issue properly but I don't think that tool you mention fits my needs. Suppose that you need to apply a certain javascript function to an specific cell for all rows. How it can be done without any nasty tricks?
For example, I have to do this if I want iterate over all the items in a table that are date inputs:

```javascript
    $("[src*='Calendar.gif']").parent().prev().each(function(i, e){
          //do stuff
    });
```
Yes, it really sucks, but I don't know how to do this in a clean way.

**Comment by toskrip** [comment]
@marctc I see, if you need to perform modifications on CRF DOM elements (not just reading values) than you sort of always end up with some triks. I don't think this is going to change, because for future OC will very likely start preffering different CRF rendering approach (XForms, Enketo).

However I can point you to a little bit nicer trick when accesing repeating grid elements. Have a look at this article:
http://www.trialdatasolutions.com/tds/howto/layoutchanges.jsp

In section: "cool, but actually I need that for a repeating item group"
it is explained how to use header property of CRF item to insert span with ID that can be used as a reference point in DOM from where you can navigate to repeating group table items.
